import HeroSection from "@/components/landing/HeroSection";
import MovieSection from "@/components/landing/MovieSection";
export const metadata = {
  title: "Movie DB - Home",
  description: "Generated by create next app",
};
export default async function Home() {
  const popularMoviesResponse = await fetch(`${process.env.BASE_API_URL}/popular`); 
  const popularMovies =await popularMoviesResponse.json()  

  const top_rated_moviesResponse = await fetch(`${process.env.BASE_API_URL}/top_rated`); 
  const top_rated_movies =await top_rated_moviesResponse.json()  

  const trendingMoviesResponse = await fetch(`${process.env.BASE_API_URL}/trending`); 
  const trendingMovies =await trendingMoviesResponse.json()  

  return (
    <>
      <HeroSection />
      <MovieSection
        popularMovies={popularMovies}
        top_rated_movies={top_rated_movies}
        trendingMovies={trendingMovies}
      />
    </>
  );
}
