import HeroSection from "@/components/landing/HeroSection";
import MovieSection from "@/components/landing/MovieSection";
export const metadata = {
  title: "Movie DB - Home",
  description: "Generated by create next app",
};
export default async function Home() {
  let popularMovies;
  let top_rated_movies;
  let trendingMovies;

  try {
    const response = await fetch(`${process.env.BASE_API_URL}/popular`);
    if (!response.ok) {
      throw new Error("Network Response not ok !!");
    }
    popularMovies = await response.json();
  } catch (error) {
    console.log("failed to fetch data");
  }
  try {
    const response = await fetch(`${process.env.BASE_API_URL}/top_rated`);
    if (!response.ok) {
      throw new Error("Network Response not ok !!");
    }
    top_rated_movies = await response.json();
  } catch (error) {
    console.log("failed to fetch data");
  }
  try {
    const response = await fetch(`${process.env.BASE_API_URL}/trending`);
    if (!response.ok) {
      throw new Error("Network Response not ok !!");
    }
    trendingMovies = await response.json();
  } catch (error) {
    console.log("failed to fetch data");
  }

  return (
    <>
      <HeroSection />
      <MovieSection
        popularMovies={popularMovies}
        top_rated_movies={top_rated_movies}
        trendingMovies={trendingMovies}
      />
    </>
  );
}
